version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: apprvd
      POSTGRES_PASSWORD: apprvd
      POSTGRES_DB: apprvd
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: 